spring:
  cloud:
    # 使用 Nacos 作为配置中心
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
  application:
    name: api
  config:
    import:
      - optional:nacos:api.yml

  main:
    allow-circular-references: true