server:
  port: 84

spring:
  application:
    name: api
  cloud:
    zookeeper:
      connect-string: localhost:2181
      max-retries: 3
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

datasource:
  host: localhost
  port: 5432
  database: match_trade
  username: postgres
  password: admin

