#server:
#  port: 84
#
#spring:
#  application:
#    name: api
#  cloud:
##    zookeeper:
##      connect-string: localhost:2181
##      max-retries: 3
#    nacos:
#      discovery:
#        server-addr: lian.yaolong.top:8848
#  redis:
#    host: yaolong.top
#    port: 6379
#    timeout: 5000
#  r2dbc:
#    username: postgres
#    password: admin
#    url: r2dbc:postgres://lian.yaolong.top:5432/match_trade
#    pool:
#      enabled: true
#
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          r2dbc: DEBUG
