FROM openjdk:8-jre

MAINTAINER yaolong <1638538651@.qq.com>

# 设置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone


# 版本
ENV APP_VERSION 0.0.1-SNAPSHOT

# 安装检查插件
ENV DOCKERIZE_VERSION v0.6.1
COPY dockerize-linux-amd64-v0.6.1.tar.gz .
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz

# 创建文件夹
RUN mkdir /app

COPY mt-engine-$APP_VERSION.jar /app/app.jar

# 检查数据库连接是否成功，成功了就运行jar
ENTRYPOINT ["dockerize", "-timeout", "5m", "-wait", "tcp://postgres:5432", "java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app/app.jar","--spring.profiles.active=prod","-c"]

EXPOSE 82
