server:
  port: 83

spring:
  application:
    name: socket
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    stream:
      default-binder: rocketmq
      bindings:
        in-trade:
          destination: trade-topic
          group: service-order
        out-order:
          destination: order-topic
          content-type: application/json

  redis:
    host: localhost
    port: 6379
    timeout: 5000

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
        web:
          reactive:
            result:
              method:
                InvocableHandlerMethod: DEBUG
    root: INFO