server:
  port: 82
spring:
  application:
    name: socket
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      default-binder: rocketmq
      bindings:
        out-trade:
          destination: trade-topic
          content-type: application/json
        in-order:
          destination: order-topic
          group: match-order


  r2dbc:
    username: postgres
    password: admin
    url: r2dbc:postgres://localhost:5432/match_trade
    pool:
      enabled: true
